groups:
recipes:
    mac_os_x:
        - applications::sublime_text_3
attributes:
    homebrewalt:
        apps:
            - awscli
            - go
            - direnv
            - rbenv
            - ruby-build
        cask_apps:
            - chefdk
